### ISSUE TITLE
Figure out a consistent way to describe sizes

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#104]
For various different components, we have "size" values:

- Icon
- Spacing & Margin tokens
- etc

How do we best express size? I just got super confused with our current setup, and eventually realised I was using the wrong size variables:

<img width="613" alt="Screenshot 2019-07-02 at 01 05 02" src="https://user-images.githubusercontent.com/376315/60473599-ae374b00-9c65-11e9-8e3e-510419de441a.png">

A few different options here:

**small, medium, large, xl, xxl**
```
<Icon xxl />
<Icon size=“xxl” />
```

**small, medium, large, extraLarge, extraExtraLarge**
```
<Icon extraExtraLarge />
<Icon size=“extraExtraLarge” />
```

**small, medium, large, xLarge, xxLarge**
```
<Icon xxLarge />
<Icon size=“xxLarge” />
```

**small, medium, large, larger, largest**
```
<Icon Largest />
<Icon size="Largest" />
```

**S, M, L, XL, XXL**
```
<Icon XXL />
<Icon size=“XXL” />
```

**Comment by tofumatt** [comment]
We ended up chatting about this one in-person, and settled on `xxSmall`, `xSmall`, `small`, `medium`, `large`, `xLarge`, and `xxLarge`. I don't like the single-character variables (eg `s`/`m`/`l`) and while I might personally prefer `extraLarge`, we found `xLarge` a fair compromise.
