### ISSUE TITLE
Icon component

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#14]
We may want to start with an open-source icon library that we can build from.

Should use SVG, obviously.

- [ ] Templates + guidelines for new icons.
- [ ] Basic Sketch components
- [ ] React components
- [ ] Documentation

**Comment by sarahmonster** [comment]
Open-source libraries to consider as a starting point:

- [Feather](https://feathericons.com/) (279 icons, MIT, nice styling)
- [Eva](https://akveo.github.io/eva-icons/#/) (480 icons, MIT, outlined and filled styles but a bit overly-rounded maybe?)
- [Remix](https://remixicon.com/) (1500 icons, Apache 2.0, outline and filled styles, but maybe too pointy?)
- [FontAwesome Free](https://fontawesome.com/icons?d=gallery&m=free) (1500 icons, "GPL-friendly")

Also a bunch listed here: https://icons8.com/welovesvg

**Comment by sarahmonster** [comment]
I'm currently leaning toward Feather stylistically and license-wise.

There are initial design guidelines here: https://github.com/feathericons/feather/issues/171

**Comment by tofumatt** [comment]
I definitely like Feather as well. Is mixing icons an issue? It seems to be less updated than other libraries, but maybe they have enough “generic” icons and we’re fine—anything else would be custom?

**Comment by sarahmonster** [comment]
Mixing icons probably won't work—what we want is to start with a base library and then build on top of that. In fact, we may well wind up tweaking some of the icons from the base library as well for stylistic and/or contenty reasons. I think it's fair to assume we'll be more forking whatever library we go for than integrating it directly. Mostly I'm just looking for a good starting point here, rather than building everything from scratch which is of course my first instinct, and it's terrible.

**Comment by sarahmonster** [comment]
Closed via #88!
