### ISSUE TITLE
Tab component

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#15]
<img width="948" alt="Screenshot 2019-06-01 at 17 45 50" src="https://user-images.githubusercontent.com/376315/58751508-370c6c80-8497-11e9-9687-c1ebd0c591bb.png">

- [ ] Basic Sketch components
- [ ] React components
- [ ] Documentation

**Comment by sarahmonster** [comment]
Pffft, that image is clearly a card, and also I definitely accidentally jumped the gun on merging this, so my double-bad.

**Comment by tofumatt** [comment]
Closed by #108.
