### ISSUE TITLE
Allow for unstyled components?

### ISSUE THREAD

**Issue by tofumatt** [octopusthink/nautilus#168]
It might be that we only want this to be true for a subset of our components, but we should at least provided unstyled versions of `Link` so that we can wrap other components with a link and not change their style.

It's likely that any component a `Link` wraps should alert that component with a special prop (or even `className`?)

We may or may not want to do this, but leaving it here for discussion/to let the idea percolate.

**Comment by sarahmonster** [comment]
Links 1000% need this! We wrap so much stuff in links.
