### ISSUE TITLE
Don't require Emotion as a dependency

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#188]
When trying to use Nautilus in a create-react-app app I was working on, I came across this error:

<img width="820" alt="Screenshot 2019-11-13 at 04 03 02" src="https://user-images.githubusercontent.com/376315/68885273-bc659f80-070c-11ea-96ef-59a867fcc1c3.png">

I wasn't sure what was going on (I wasn't trying to use Emotion in the app yet, just to hook up Nautilus), but installing Emotion in my app solved the problem.

We should ideally not require Emotion as a dependency (since not everyone would want to use it), or, if it's strictly required, we should install it along with Nautilus itself. (I don't know if that's possible, but it feels like it should be!)

**Comment by tofumatt** [comment]
Or rather: we _should_ explicitly require emotion as a dependency, because our components rely on it. I'll create a PR to address this, it's easy 😄
