### ISSUE TITLE
Link: Bump opacity of external link indicator

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#217]
This is just a wee bit much:

<img width="312" alt="Screenshot 2020-03-31 at 20 55 59" src="https://user-images.githubusercontent.com/376315/78070824-5b292a80-7394-11ea-9294-b526ca596112.png">

A much subtler one still provides value, but doesn't quite disrupt the reading flow in the same way:

<img width="218" alt="Screenshot 2020-03-05 at 19 54 16" src="https://user-images.githubusercontent.com/376315/78071127-d7237280-7394-11ea-92c3-f231b4055bfe.png">

**Comment by tofumatt** [comment]
Ohhhh, agreed, that is an awesome call.
