### ISSUE TITLE
Colour guidelines

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#22]
![Palette](https://user-images.githubusercontent.com/376315/57986040-b0ec3100-7a67-11e9-9ed0-0d8dfecc6e38.png)

^ this will require some tweaking, but might be best done with a colour generator, once we have one. For now, we'll run with these variables until we have a generator!

- [ ] Define colour variables in theme (palette and semantic and theme variables!)
- [ ] Write documentation.
- [ ] Apply variables to all components.

**Comment by sarahmonster** [comment]
Themeable colour variables are already in place (and being built up as we implement more components). 

So, I think what we mostly need to do here is add docs. I've got a draft of those ready for review here:
https://www.notion.so/octopusthink/Colour-9b39ffaa4ed044358f1b4e34b29d0b76

@tofumatt if you'd be able to give it a review I can polish it up and add it to our docs.

**Comment by tofumatt** [comment]
I left some comments and tweaks; everything up until the “Form” section looks great!

Did you want me to review the “Form” section at the bottom as well? It seems a bit less related and I don’t really understand the code in there.

**Comment by sarahmonster** [comment]
Nope! That's just my notes for how branding/themeing will work but it definitely will belong in the Form section. I'll revise a bit more and make a PR. Thanks for the edits!
