### ISSUE TITLE
Design principles

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#23]
Basically this is just writing/tweaking some documentation and maybe making it look nice.

![1  Principles](https://user-images.githubusercontent.com/376315/57985969-e2183180-7a66-11e9-95d2-775856851aae.png)

**Comment by sarahmonster** [comment]
@tofumatt for this an a whole slew of other things, I'm going to wind up writing a whole lot of documentation. How do you feel about this process:

1. Write initial draft in Notion.
2. Collaborate back-and-forth there until we're happy.
3. Convert to Markdown & create a PR.
4. Ask for PR review.
5. Merge.

My thinking is that Notion (or even Google docs) will make it simpler to fine-tune text and collaborate back and forth, and then we can move the docs here once they're a bit more stable.

**Comment by sarahmonster** [comment]
I'm going to take that as a "yes, of course that's cool!"

Here's my first draft at design principles: https://www.notion.so/octopusthink/Principles-715bdbf3e22143bba07f8eeefea9b3e4

Would ❤️ a review whenever time allows!

**Comment by tofumatt** [comment]
Absolutely perfect; I just wish Notion had a "reaction" feature I could use to give it 👍 or the like. I'm not sure I can find a single fault or thing to change. Very nice 😄
