### ISSUE TITLE
Set up infrastructure

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#24]
- [x] Continuous Integration/Tests
- [x] Continuous Deployment—Deployment of website
- [x] Continuous Deployment—packaging of `npm` package
- [x] ~Continuous Deployment—notifications of built site for testing~
- [x] Improvements to Azure Pipeline file (separate out different tasks into their own steps/stages, instead of combining `npm run lint` and `npm run test:all`)

**Comment by tofumatt** [comment]
A very early-on CI/CD setup is in place that pushes the styleguide (alongside any PR) to our Github Pages site for Nautilus. I'm just getting started with Azure Pipelines so they'll get improved, but it's a start. I'll update this issue to describe what's needed for the project right now.

**Comment by tofumatt** [comment]
Closed this one out with #77 I _think_. 🤞
