### ISSUE TITLE
PageTitle component

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#49]
Possible names:

- PageTitle
- ScreenTitle
- ViewTitle

I expect that a lot of sites will wind up having a SiteTitle component or variable in some form or another, so we'd probably want to avoid just plain old Title as a name since it could potentially be confusing.

This should use the PageTitle styles from the `mixins.js` file and more or less follow Heading conventions with the following exceptions:

- Should use an h1 (probably with no possibility of a level override?)
- Only one per screen/page/view allowed.
- Do we want to use Sentence case here or switch to Title Case Instead? Title case could actually be nice, but I have mixed feelings there.
- Can allow for more expressive visual styling (gradients inside the text, funky effects, weird placement, etc).

**Comment by tofumatt** [comment]
I'm not a huuuuuuge fan of `PageTitle` because in an app context it's less about a page. And then in an editorial context: it's less about a `Screen`. `View` seems too narrow. A generic `<Title>` feels like it works best, but I guess calling it a `PageTitle` even in an app isn't so bad 😆
