### ISSUE TITLE
Change "numbered" to "ordered"

### ISSUE THREAD

**Issue by tofumatt** [octopusthink/nautilus#71]
I think we should be creating ordered lists using the `ordered` prop instead of the current `numbered` prop. First of all: some ordered lists/styles will use letters over numbers, and two: it's about order/sequence, not about numbers. A numbered list could be a list with numbers _in_ it. The point of an `<ol>` is that the _order_ matters, not that numbers are there.

I think we should change the prop. We _could_ provide `numbered` as a prop alias, but I don't like that. We use `<ol>` on the web, so let's use "order" here too!

**Comment by sarahmonster** [comment]
I think "numbered" is a bit more human-friendly (I need to think more about what "ordered" means), but.... it's not a hill I'm willing to die on. Or that I have especially strong feelings about, really. I think you're right and it does make more semantic sense, even though I think numbering a list with letters is monstrous. 👹

**Comment by tofumatt** [comment]
I actually agree on the last point. But I think it makes sense to be semantic. We can add an alias in the future if you're still really getting tripped up.

**Comment by sarahmonster** [comment]
👍

**Comment by sarahmonster** [comment]
For reference: I don't think we need to inherit HTML's inherent weirdness where it doesn't make sense, but it actually is more semantically correct here, even if that's maybe not how humans instinctively think about it.

**Comment by tofumatt** [comment]
Agreed. There are places where we don't: I actually think having separate list types is kinda weird like that and wouldn't advocate a separate `<OrderedList>` component. Equally, I might go with `description` over `alt` for images...

**Comment by sarahmonster** [comment]
If nothing else, "ordered" is much better than having to know "unordered" and "ordered". Yuck.
