### ISSUE TITLE
Allow for serving Nautilus on a custom hostname

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#89]
This is a super minor issue, but I sometimes forget which port things are being served over, and I'd love to be able to use a custom hostname to view Nautilus in my browser.

I think this is doable with webpack: https://stackoverflow.com/a/31252683

Not sure if there might be issues with attempting to implement that, though—I don't want everyone who runs Nautilus to be forced to edit their host files just for my convenience; that's absolutely monstrous.

Also, this is obviously super not-urgent.

**Comment by tofumatt** [comment]
You should be able to set this on the command line for your setup, but it’s not something I think we should make a default in the config/package.json. Our `npm start` command will take extra arguments to the styleguidist cli command, which can be customised: https://react-styleguidist.js.org/docs/configuration.html#serverhost

At least, I’m assuming passing those props would work. I can try later when I’m not on mobile!

- Matt (Sent from mobile) | https://octopusthink.com

**Comment by tofumatt** [comment]
So it looks like React Styleguidist only supports this via its config file and not via the CLI. I could allow environment variables to override it, but the main issue to note is that the URL is output after you run `npm start`...

You can edit your own hosts file to point to `0.0.0.0`, where it's run by default. And we could certainly use a different port if you like. 🤷‍♂

But I think this largely something you can personally config 😏

**Comment by sarahmonster** [comment]
Sounds like it's not needed or easily done—let's close and I can modify my own config if I want something more custom here. 👍
